### ISSUE TITLE
running error

### ISSUE THREAD

**Issue by chawdamrunal** [alessandrodd/apk_api_key_extractor#7]
python3 main.py
Traceback (most recent call last):
  File "main.py", line 12, in <module>
    from mongodb_dump import MongoDBDump
  File "/home/mru/apk_api_key_extractor/mongodb_dump.py", line 12, in <module>
    import config
  File "/home/mru/apk_api_key_extractor/config.py", line 11, in <module>
    with open(os.path.join(__location__, CONFIG_PATH), 'r') as ymlfile:
FileNotFoundError: [Errno 2] No such file or directory: '/home/mru/apk_api_key_extractor/config.yml'

**Comment by alessandrodd** [comment]
From the [README](README.md)

> $ git clone --recursive https://github.com/alessandrodd/apk_api_key_extractor.git
$ cd apk_api_key_extractor
$ **cp config.example.yml config.yml**
$ pip3 install -r requirements.txt
$ python3 main.py
